greeting: |
  Привет!
  Это AI Optic Bot.
  Что я могу для вас сделать?

  Для повторного вызова меню отправьте любое сообщение.
keyboard:
  material: Материал оправы
  type: Тип оправы
  tag: Найти оправу по метке
buttons:
  material: |
    Для определения материала оправы, пожалуйста, пришлите фотографию очков.
    Пример фото:
  material_img_path: 'img/frame.jpg'
  tag: |
    Чтобы найти оправу по метке, пришлите фото метки как можно отчетливее и крупнее.
    Пример фото:
  tag_img_path: 'img/tag.jpg'
  type: |
    Для определения типа оправы, пожалуйста пришлите фотографию очков.
    Пример фото:
  type_img_path: 'img/frame.jpg'
predict:
  started: Добавлено в очередь
  material:
    is_plastic: Я думаю, что материал оправы - пластик.
    is_metall: Я думаю, что материал оправы - металл.
  type:
    is_line: Я думаю, что тип оправы - леска.
    is_rim: Я думаю, что тип оправы - ободок.
    is_sleeve: Я думаю, что тип оправы - втулка.
  tag:
    result: |
      Маркировка: {full_tag}
      Модель: {tag}
      Ширина линзы (мм): {lens_size}
      Мост (мм): {bridge_size}
      Ширина оправы (мм): {earpiece_length}
      Длина заушника (мм): {shackle_length}
    is_unknown: Не могу найти оправу в базе.
  is_unknown: Не могу определить материал оправы.
  is_not_glasses: Не могу определить очки на фото, попробуйте другое фото.
what_to_do: Чем могу помочь?
